name: Deploy FastAPI to Render

on:
  push:
    branches:
      - main  # Déploie à chaque push sur la branche principale
  pull_request:
    branches:
      - main  # Vérifie le code sur chaque pull request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

        # Exécuter les tests (si vous avez des tests)
      - name: Run tests
        run: |
          pytest  # Remplacez cela par la commande appropriée si vous avez des tests à faire

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }} # Clé API Render
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }} # ID du service Render
        run: |
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          --data '{}'


    

