name: Render Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout render-oss/deploy-action
        uses: actions/checkout@v3
        with:
          repository: render-oss/deploy-action
          path: render-oss/deploy-action

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.11'  # Spécifiez la version Python que vous souhaitez

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r  app/requirements.txt

      # 4. Exécuter les tests (si vous avez des tests)
      - name: Run tests
        run: |
          pytest  # Remplacez cela par la commande appropriée si vous avez des tests à faire

      # 5. Déployer sur Render
      - name: Build and deploy to Render
        uses: ./render-oss/deploy-action/v1 # Use the local path
        with:
          #serviceId: YOUR_SERVICE_ID
          #instanceId: YOUR_INSTANCE_ID
          apiKey: ${{ secrets.RENDER_API_KEY }}
