name: Deploy to Streamlit with ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Tests unitaires
        run: pytest Tests/
      - name: Start MLflow server
        run: |
          mlflow server --host 0.0.0.0 --port 5000 &
      - name: Expose with ngrok
        run: |
          export NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}
          pyngrok http 5000
          export MLFLOW_UI_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "::set-output name=MLFLOW_UI_URL::$MLFLOW_UI_URL"
      - name: Run Streamlit app
        run: |
          streamlit run app.py --server.port 8501 &
          # Attendez que l'application Streamlit soit démarrée
          sleep 10
          # Affichez l'URL publique ngrok dans les logs
          echo "Application Streamlit accessible sur : ${{ steps.expose-with-ngrok.outputs.MLFLOW_UI_URL }}"
