name: Deploy to Streamlit with ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Tests unitaires 
        run: pytest Tests/
      - name: Start MLflow server
        run: |
          nohup mlflow server --host 127.0.0.1 --port 5000 & 
      - name: Expose with ngrok
        id: expose-with-ngrok 
        run: |
          export NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}
          pyngrok http 5000 &
          sleep 5 
          MLFLOW_UI_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "MLFLOW_UI_URL=$MLFLOW_UI_URL" >> $GITHUB_ENV
      - name: Run Streamlit app
        run: |
          streamlit run app.py --server.port 8501 &
          sleep 10 
          echo "Application Streamlit accessible sur : $MLFLOW_UI_URL"
