name: Deploy to Render via Deploy Hook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t my-ml-api .

      - name: Log in to Render
        run: |
          echo ${{ secrets.RENDER_API_KEY }} | docker login --username render --password-stdin

      - name: Push Docker image to Render
        run: |
          docker tag my-ml-api registry.render.com/Satou DIOP/my-fastapi-app:latest
          docker push registry.render.com/Satou DIOP/my-fastapi-app:latest

      - name: Trigger Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }} \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{}'
