name: Deploy to Heroku (Docker)

on:
  push:
    branches:
      - main  # Déclenche le déploiement sur push vers main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pour éviter les problèmes avec les push shallow

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        run: heroku container:login

      - name: Deploy to Heroku using Docker
        run: |
          heroku container:push web -a $HEROKU_APP_NAME
          heroku container:release web -a $HEROKU_APP_NAME

      - name: Check Heroku logs (debug)
        run: heroku logs --tail -a $HEROKU_APP_NAME
