name: Deploy FastAPI to Render

on:
  push:
    branches:
      - main  # Déploiement automatique quand on push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Deploy to Render via API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Clé API Render
          # SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}  # ID du service Render
        run: |
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          --data '{}'
