name: Déployer sur Heroku (sans Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
      - name: Extraire le code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Configurer Heroku CLI  
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installer Heroku CLI
        run: npm install -g heroku

      - name: Authentification Heroku
        run: heroku login -i --key ${{ secrets.HEROKU_API_KEY }}

      - name: Ajouter remote Heroku
        run: git remote add heroku https://git.heroku.com/${{ env.HEROKU_APP_NAME }}.git

      - name: Synchroniser avec Heroku
        run: git pull heroku main --rebase 

      - name: Déployer sur Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          procfile: "web: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
