name: Déployer sur Heroku (sans Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

    steps:
      - name: Extraire le code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Récupérer tout l'historique Git

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Installer Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Authentification Heroku
        run: heroku login -i -a ${{ secrets.HEROKU_APP_NAME }}

      - name: Configurer les informations d'identification Git pour Heroku
        run: |
          git config --global user.email "${{ secrets.HEROKU_EMAIL }}"
          git config --global user.name "SatouMaodo"  # Ou votre nom d'utilisateur GitHub

      - name: Déployer sur Heroku
        run: |
          git push heroku HEAD:main  # Déployer la branche actuelle vers Heroku main
