name: Déployer sur Heroku (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
      - name: Extraire le code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Se connecter au registre de conteneurs Heroku
        run: heroku container:login

      - name: Construire et pousser l'image Docker
        run: heroku container:push web -a $HEROKU_APP_NAME

      - name: Publier l'image Docker
        run: heroku container:release web -a $HEROKU_APP_NAME

      - name: Vérifier les journaux Heroku (débogage)
        run: heroku logs --tail -a $HEROKU_APP_NAME
