name: Continuous Deployment to Streamlit Cloud

on:
  push:
    branches:
      - main  # Déployer sur la branche principale
  pull_request:
    branches:
      - main  # Déployer lors des pull requests sur la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Spécifiez la version Python que vous souhaitez

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Exécuter les tests (si vous avez des tests)
      - name: Run tests
        run: |
          pytest  # Remplacez cela par la commande appropriée si vous avez des tests à faire

      # 5. Déployer sur Streamlit Cloud
      - name: Deploy to Streamlit Cloud
        run: |
          echo "Streamlit Cloud prendra en charge le déploiement de l'application."
