name: Continuous Deployment to Streamlit Cloud

on:
  push:
    branches:
      - main  # Déployer sur la branche principale
  pull_request:
    branches:
      - main  # Déployer lors des pull requests sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.11' 

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Exécuter Streamlit en mode headless
      - name: Run Streamlit
        env:
          STREAMLIT_SERVER_HEADLESS: "False"  # Activer le mode headless pour Streamlit
        run: |
          streamlit run app.py
