name: Deploy to Streamlit with ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Tests unitaires 
        run: pytest Tests/
      - name: Start MLflow server
        run: |
          nohup mlflow server --host 0.0.0.0 --port 5000 & 
      - name: Run Streamlit app
        run: |
          streamlit run app.py --server.port 8501 &
          sleep 10 



