name: Deploy to Streamlit

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Add this step if it's missing
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install streamlit
          
      - name: Tests unitaires
        run: pytest Tests/

      - name: Start MLflow server
        run: |
          mlflow server --host 0.0.0.0 --port 5000 &
      - name: Deploy to Streamlit
        uses: streamlit/streamlit-github-actions@v1 # Make sure the name is correct
        with:
          token: ${{ secrets.STREAMLIT_TOKEN }}
          branch: main
          create_new_app: true  
          app_name: "Interface de suivi MLflow"
          app_file: app.py
          env_vars: MLFLOW_UI_URL="https://d64d-104-197-221-124.ngrok-free.app"
