name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow
          pip install gunicorn
          pip install pytest
          # Install the Heroku CLI 
          curl https://cli-assets.heroku.com/install.sh | sh
      # name: Run pytest
       # run: pytest Tests/

      - name: Login to Heroku
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | heroku auth:token
          
      - name: Set Heroku git remote
        run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}

      # Add these steps for deployment
      - name: Build and push Docker image to Heroku
        run: |
          heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
          heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
