name: Deploy to Railway

on:
  push:
    branches:
      - main  # Ou la branche que vous souhaitez déployer

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway up --detach
        env:
          RAILWAY_PROJECT: ${{ secrets.RAILWAY_PROJECT }}
          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE }} 
          # Autres variables d'environnement nécessaires à votre application, 
          # comme MLFLOW_TRACKING_URI, etc.
