name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install mlflow
          pip install pyngrok

      - name: Install Heroku CLI
        run: |
          sudo snap install --classic heroku
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Login to Heroku
        run: |
          unset HEROKU_API_KEY
          heroku login -i
          export HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}

      - name: Set Heroku git remote
        run: heroku git:remote -a ${{ env.HEROKU_APP_NAME }}

      - name: Set Heroku config vars
        run: |
          heroku config:set MLFLOW_TRACKING_URI=${{ env.MLFLOW_TRACKING_URI }} -a ${{ env.HEROKU_APP_NAME }}
          heroku config:set MLFLOW_ARTIFACT_ROOT="mlruns/1/e168c89c821b4680a3a92d7ee0ed2e28/artifacts" -a ${{ env.HEROKU_APP_NAME }}

      - name: Download model and artifacts
        run: |
          mkdir -p "mlruns/1/e168c89c821b4680a3a92d7ee0ed2e28/artifacts"
      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:main

      - name: Scale web dyno
        run: heroku ps:scale web=1 -a ${{ env.HEROKU_APP_NAME }}

      - name: Start MLflow API server
        run: heroku run "mlflow models serve -m model_artifacts --no-conda -h 0.0.0.0 -p $PORT" -a ${{ env.HEROKU_APP_NAME }}

