name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_MODEL_URI: models:/Projet7_Scoring_model/Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install mlflow --upgrade  # Upgrade MLflow

      - name: Install mlflow for download
        run: pip install mlflow --upgrade

      - name: Download MLflow model
        run: |
          mlflow models download -m ${{ env.MLFLOW_MODEL_URI }} -o P7_Modele_de_scoring
          
      - name: Login to Heroku Container Registry
        run: heroku container:login

      - name: Build and push Docker image
        run: |
          # Assuming your Dockerfile is in the root directory
          # And you want to copy the model to /app/P7_Modele_de_scoring in the image
          docker build -t ${{ env.HEROKU_APP_NAME }} . --build-arg MLFLOW_MODEL_URI=${{ env.MLFLOW_MODEL_URI }}
          docker tag ${{ env.HEROKU_APP_NAME }} registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
          

      - name: Release Docker image
        run: heroku container:release web -a ${{ env.HEROKU_APP_NAME }}

      - name: Set Heroku config vars
        run: |
          heroku config:set MLFLOW_TRACKING_URI=${{ env.MLFLOW_TRACKING_URI }} -a ${{ env.HEROKU_APP_NAME }}
