name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
      # Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Évite le shallow clone dès le départ

      # Mise en cache des dépendances Python
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Installer les dépendances Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip --quiet
          pip install -r requirements.txt --quiet

      # Installer l'outil Heroku CLI
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # Débloquer le shallow clone de GitHub Actions
      - name: Unshallow the repository
        run: git fetch --prune --unshallow

      # Déploiement sur Heroku via Git
      - name: Deploy to Heroku
        run: |
          git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
