name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow
          pip install gunicorn
          pip install heroku # Install Heroku CLI using pip
      - name: Login to Heroku
        run: heroku login -i --key ${{ secrets.HEROKU_API_KEY }} # Non-interactive login

      - name: Set Heroku git remote
        run: heroku git:remote -a ${{ env.HEROKU_APP_NAME }}

      - name: Set Heroku config vars
        run: |
          heroku config:set MLFLOW_TRACKING_URI=${{ env.MLFLOW_TRACKING_URI }} -a ${{ env.HEROKU_APP_NAME }}
      - name: Deploy to Heroku
        run: |
          heroku config:set HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} -a ${{ env.HEROKU_APP_NAME }}
          heroku config:set HEROKU_APP_NAME=${{ env.HEROKU_APP_NAME }} -a ${{ env.HEROKU_APP_NAME }}
          heroku config:set HEROKU_EMAIL=${{ secrets.HEROKU_EMAIL }} -a ${{ env.HEROKU_APP_NAME }}
          git push heroku main:main # Push to the main branch
