name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Clé API Heroku
      HEROKU_APP_NAME: mon-application-heroku  # Nom de l'application Heroku
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install mlflow
          pip install pyngrok

      - name: Login to Heroku
        run: heroku login -i -a ${{ env.HEROKU_APP_NAME }}

      - name: Set Heroku git remote
        run: heroku git:remote -a ${{ env.HEROKU_APP_NAME }}

      - name: Set Heroku config vars
        run: |
          heroku config:set MLFLOW_TRACKING_URI=${{ env.MLFLOW_TRACKING_URI }} -a ${{ env.HEROKU_APP_NAME }}

      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:main

      - name: Start MLflow server
        run: |
          heroku run "mlflow server --backend-store-uri ${{ env.MLFLOW_TRACKING_URI }} --default-artifact-root ./artifacts --host 0.0.0.0 --port $PORT &" -a ${{ env.HEROKU_APP_NAME }}
          
      - name: Expose MLflow UI with ngrok
        run: |
          pyngrok config add-auth ${{ secrets.NGROK_AUTH_TOKEN }}
          heroku run "pyngrok http $PORT" -a ${{ env.HEROKU_APP_NAME }}
