name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install mlflow
          pip install pyngrok

      - name: Install Heroku CLI
        run: |
          sudo snap install --classic heroku
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Login to Heroku
        run: |
          unset HEROKU_API_KEY
          heroku login -i
          export HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}

      - name: Set Heroku git remote
        run: heroku git:remote -a ${{ env.HEROKU_APP_NAME }}

      - name: Set Heroku config vars
        run: |
          heroku config:set MLFLOW_TRACKING_URI=${{ env.MLFLOW_TRACKING_URI }} -a ${{ env.HEROKU_APP_NAME }}
          heroku config:set MLFLOW_ARTIFACT_ROOT="./Scoring_model" -a ${{ env.HEROKU_APP_NAME }}

      - name: Update Heroku CLI # Solution 2: Mise à jour de Heroku CLI
        run: heroku update

      - name: Add Heroku SSH buildpack # Solution 1: Ajout du buildpack SSH avec le nom correct
        run: heroku buildpacks:add heroku/heroku-ssh -a ${{ env.HEROKU_APP_NAME }} # Correction: Ajout de ${{ env.HEROKU_APP_NAME }}

      - name: Deploy to Heroku
        run: git push -f git@heroku.com:${{ env.HEROKU_APP_NAME }}.git HEAD:main

      - name: Start MLflow server
        run: |
          heroku run -d "mlflow server --backend-store-uri ${{ env.MLFLOW_TRACKING_URI }} --default-artifact-root $MLFLOW_ARTIFACT_ROOT --host 0.0.0.0 --port $PORT" -a ${{ env.HEROKU_APP_NAME }}

      - name: Expose MLflow UI with ngrok
        run: |
          pyngrok config add-auth ${{ secrets.NGROK_AUTH_TOKEN }}
          heroku run -d "ngrok http $PORT --log=stdout" -a ${{ env.HEROKU_APP_NAME }}
