name: pytest

on:
  push:
    branches:
      - main  # Ou la branche sur laquelle vous voulez exécuter les tests
  pull_request:
    branches:
      - main  # Ou la branche sur laquelle vous voulez exécuter les tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'  # Remplacez par votre version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt  

      - name: Run pytest
        run: pytest
